name: Development Continuous Deployment (CD)

on:
  push:
    branches: 
      - '*'

jobs:
  build_and_deploy:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Temporary .env
        run: |
          touch .env
          echo ${{ secrets.ENV_FILE }} >> .env

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This action will handle the deployment
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.heroku_app_name}} # replace with your app's name
          heroku_email: "hyperiontech.capstone@gmail.com" # replace with your Heroku email
          healthcheck: "https://infinite-reaches-07482.herokuapp.com/" # replace with your app's URL
