
name: Continuous Intergration (CI)

on:
  push:
    branches: 
      - '*'

jobs:
  build_and_deploy:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Temporary .env
        run: |
          touch .env
          echo ${{ secrets.ENV_FILE }} >> .env
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Run Frontend Tests
        run: ng test --watch=false --browsers=ChromeHeadless
        working-directory: frontend
        
      - name: Install Backend Dependencies
        run: npm install
        working-directory: backend
        
      - name: Start Backend
        run: npm run build
        working-directory: backend
      
      - name: Run test
        run: npm test
        working-directory: backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
