name: Development Continuous Integration (CI)

on:
  push:
    branches:
      - develop

jobs:
  build_and_test:
    environment: Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Temporary .env
        run: |
          touch .env
          echo ${{ secrets.ENV_FILE }} >> .env

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Install xvfb
        run: sudo apt-get install xvfb -y

      - name: Start xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          echo "DISPLAY=:99.0" >> $GITHUB_ENV

      - name: Lint All Projects
        run: npm run lint

      - name: Create Coverage Report
        run: npm run test:coverage


      - name: Build Angular Application
        run: npm run build

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: hyperiontech.capstone@gmail.com
          healthcheck: "https://infinite-reaches-07482.herokuapp.com/"

        # new flow
