name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
      with:
        heroku_api_key: ${{secrets.400d259f-6750-4738-8a43-33fb07dd8d19}}
        heroku_app_name: "infinite-reaches-07482" # Must be unique in Heroku
        heroku_email: "hyperiontech.capstone@gmail.com"
