name: Development Continuous Deployment (CD)

on:
  push:
    branches: [ develop ]

jobs:
  build_and_deploy:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Temporary .env
        run: |
          touch .env
          echo ${{ secrets.ENV_FILE }} >> .env

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Login to Heroku
        run: |
          heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        run: |
          git push heroku ${GITHUB_REF#refs/heads/}:master
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
